sudo: required
dist: trusty

language: python
python:
  - "3.6"

# install system dependencies here with apt-get.
before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y python3 python3-pip python-dev build-essential

# install python dependencies including this package in the travis
# virtualenv
install:
  # Install Python dependencies
  - pip3 install -r /home/travis/build/roedoejet/mothertongues/requirements.txt
  # Install testing requirements
  - pip3 install coverage
  - pip3 install coveralls
  # Install mtd
  - cd /home/travis/build/roedoejet/mothertongues && pip3 install -e .
# before_script:
#     - gunicorn mtd:app --bind 0.0.0.0:5000 --daemon
    
# commands to run the testing suite. if any of these fail, travic lets us know
script: 
    # - py.test
    - cd /home/travis/build/roedoejet/mothertongues && python3 run_tests.py dev
    - cd /home/travis/build/roedoejet/mothertongues && coverage run run_tests.py dev

# commands to run after the tests successfully complete
after_success:
  - coveralls